### PR TITLE
Fix ios14

### PR DESCRIPTION
**Pull request by facetious**
This corrects the command interaction with the secure socket server for Start and Stop operations.

**Note:** I'm not sure about removing the detach; when I had the detach still in there, the debugserver was terminated on a partial read and the app exits immediately.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Excellent @facetious greatly appreciated 🤗  We'll publish an rc of this and do some more testing and contact you via Slack on anything further!

**Comment by facetious** [comment]
After replacing the binary locally in my node_modules, this does enable the CLI to work correctly to stop and start apps, but it doesn't _restart_ apps. I don't know if that's just a race condition, if the CLI needs to be updated to wait appropriately, or if this tool needs to add in an artificial delay at the end of each command.

**Comment by rigor789** [comment]
@facetious thanks for the changes - it does seem to fix most of the issues.

Some observations on my side - while debugging the changes:
 - detaching/disconnecting the socket kills the app - that's likely why commenting the detach works
 - subsequent start commands don't start the app - only the first one
 - same for stop commands - somehow the `can_send_kill` returns false for subsequent runs, the response on first call is a hex string, while other calls are empty strings (https://github.com/NativeScript/ios-device-lib/blob/144212acad5d2c1f1cd5ff25be8f5ba3eaf6691e/IOSDeviceLib/GDBHelper.cpp#L100-L119). Bypassing the check doesn't solve it either, sending `k` doesn't do anything only on the first run.
 - maybe related to not detaching - since we may be sending the `k` (kill) command to an already stopped process, rather than the new/fresh process.

**Comment by facetious** [comment]
@rigor789 I dug in a bit more to this issue and this branch is now able to properly start and stop an app multiple times. Some notes:

1. Killing the debugger still kills the app. 🤷 
2. Requesting a "stop" to an app that isn't running actually starts the app and then reports a successful stop. 🤷 
3. If an app is spitting out a lot of stdout, the ios-device-lib process might be unable to communicate; not sure on that one, but an infinite loop waiting for silence seems like it's asking for trouble.

**Comment by facetious** [comment]
@rigor789 I've rebased and squashed all changes. Start / stop now function as expected and killing the debugger no longer kills the app.

**Review by NathanWalker — APPROVED** [review]

**Comment by facetious** [comment]
Hey what ever happened to this? @NathanWalker @rigor789

**Comment by rigor789** [comment]
@facetious currently used as `0.8.0-rc.1` in the CLI - we should probably merge it and bump it to stable and update it in CLI with the next release

**Comment by farfromrefug** [comment]
@rigor789 could we merge this? it is kind of weird to have the repo not in sync with what is used in production by everyone...

**Pull request merged**
